export const emptyPageObject = {
  id: null,
  dataset_id: '',
  iframe_html: null,
  iframe_title: null,
  hyperlink_url: null,
  hyperlink_title: null,
  hyperlink_new_tab: null,
  is_effective_identity_required: false,
  last_refresh_date: '',
  last_refresh_status: '',
  preview_pages: false,
  report: '',
  report_id: '',
  role: '',
  role_id: null,
  row_level_role: '',
  source_status: null,
  type: null,
  workspace: '',
  workspace_id: '',
  roles: [],
  users: []
}
